//! Reward-claim price impact estimator (issue #355).
//!
//! Read-only helper that approximates how much a large reward claim, if sold
//! into the reward token's DEX liquidity pool immediately after claiming,
//! would move the reward token's price. This helps large stakers time their
//! claims responsibly instead of dumping into thin liquidity.
//!
//! The estimate queries the destination DEX pool for its current reserves via
//! a cross-contract `get_reserves()` call, then applies a constant-product
//! approximation. It is intrinsically approximate — real impact depends on
//! order routing and concurrent trades — and it never changes on-chain state
//! nor requires authorization.

use soroban_sdk::{contractimpl, contracttype, Address, Env};

use crate::balance;
use crate::vault::{VaultContract, VaultContractClient};

/// Minimal interface for the DEX liquidity pool this estimator queries. The
/// pool must expose its reserves as `(reward_reserve, quote_reserve)` — the
/// first element is treated as the reward token's depth.
///
/// Only `DexPoolClient`, generated by `contractclient`, is ever called; the
/// trait itself exists to declare the client's shape.
#[allow(dead_code)]
#[soroban_sdk::contractclient(name = "DexPoolClient")]
pub trait DexPoolInterface {
    fn get_reserves(env: Env) -> (i128, i128);
}

/// Basis-point scale (10 000) used throughout the impact math.
const BPS: i128 = 10_000;

#[contracttype]
#[derive(Clone, Debug, PartialEq)]
pub struct PriceImpactEstimate {
    /// The user's currently pending (unclaimed) reward — the amount being
    /// evaluated for claim-and-sell.
    pub claim_amount: i128,
    /// Approximate price impact in basis points (1 bps = 0.01%).
    pub estimated_impact_bps: i128,
    /// Largest claim whose impact stays under 100 bps (1%).
    pub recommended_max_claim: i128,
    /// Current reward-token liquidity depth reported by the DEX pool.
    pub pool_liquidity: i128,
}

#[cfg_attr(not(test), contractimpl)]
impl VaultContract {
    /// Estimate the DEX price impact of claiming `user`'s pending reward and
    /// (hypothetically) selling it into `dex_pool`.
    ///
    /// Read-only: no auth required, no state changes. Reaches out to
    /// `dex_pool` via `get_reserves()`; if the pool is unreachable or does not
    /// implement that interface, returns a zero-impact estimate gracefully.
    pub fn estimate_claim_price_impact(
        env: Env,
        user: Address,
        dex_pool: Address,
    ) -> PriceImpactEstimate {
        let claim_amount = balance::get_accrued_reward(&env, &user);

        let pool = DexPoolClient::new(&env, &dex_pool);
        // `get_reserves()` returns `(reward_reserve, quote_reserve)`; the first
        // element is the reward token's liquidity depth.
        let (reward_reserve, _quote_reserve) = match pool.try_get_reserves() {
            Ok(Ok(pair)) => pair,
            _ => {
                return PriceImpactEstimate {
                    claim_amount,
                    estimated_impact_bps: 0,
                    recommended_max_claim: 0,
                    pool_liquidity: 0,
                };
            }
        };

        let pool_liquidity = reward_reserve.max(0);

        // No depth, no claim, or a negligible claim (<0.01% of liquidity) —
        // returning zero keeps the estimate meaningful rather than emitting a
        // sub-bps rounding artifact.
        if pool_liquidity <= 0
            || claim_amount <= 0
            || claim_amount.saturating_mul(BPS) < pool_liquidity
        {
            return PriceImpactEstimate {
                claim_amount,
                estimated_impact_bps: 0,
                recommended_max_claim: 0,
                pool_liquidity,
            };
        }

        // Constant-product approximation (issue #355):
        //   impact_bps = claim_amount * 10000 / (pool_liquidity + claim_amount)
        let estimated_impact_bps = claim_amount
            .saturating_mul(BPS)
            .checked_div(pool_liquidity.saturating_add(claim_amount))
            .unwrap_or(0);

        // Claim size at which impact reaches 100 bps (1%):
        //   claim * 10000 / (L + claim) = 100  =>  claim = 100 * L / 9900
        let recommended_max_claim = pool_liquidity.saturating_mul(100) / 9_900;

        PriceImpactEstimate {
            claim_amount,
            estimated_impact_bps,
            recommended_max_claim,
            pool_liquidity,
        }
    }
}